# Generated by Django 5.1.2 on 2025-04-21 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='User')),
                ('mid', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Message ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 5, 0), verbose_name='Time:')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
