# Generated by Django 5.2 on 2025-04-30 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmid', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Pending Message ID')),
                ('inline_message_id', models.CharField(max_length=255, verbose_name='Inline Message ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 5, 0), verbose_name='Time:')),
            ],
            options={
                'verbose_name': 'Pending Message',
                'verbose_name_plural': 'Pending Messages',
            },
        ),
    ]
