# Generated by Django 5.2 on 2025-04-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_db', '0002_pendingmessagesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmessagesmodel',
            name='chosen_id',
            field=models.CharField(default=1, max_length=255, verbose_name='Chosen ID'),
            preserve_default=False,
        ),
    ]
